package com.ytc.app5.model;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_book.id
     *
     * @mbggenerated Fri Feb 04 12:31:20 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_book.add_time
     *
     * @mbggenerated Fri Feb 04 12:31:20 CST 2022
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_book.author
     *
     * @mbggenerated Fri Feb 04 12:31:20 CST 2022
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_book.cover_photo
     *
     * @mbggenerated Fri Feb 04 12:31:20 CST 2022
     */
    private String coverPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_book.name
     *
     * @mbggenerated Fri Feb 04 12:31:20 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_book.price
     *
     * @mbggenerated Fri Feb 04 12:31:20 CST 2022
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_book.status
     *
     * @mbggenerated Fri Feb 04 12:31:20 CST 2022
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_book.press_id
     *
     * @mbggenerated Fri Feb 04 12:31:20 CST 2022
     */
    private Press press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_book.v_book_type_id
     *
     * @mbggenerated Fri Feb 04 12:31:20 CST 2022
     */
    private BookType bookType;

    public Book() {
    }

    public Book(Long id, Date addTime, String author, String coverPhoto, String name, Long price, Long status, Press press, BookType bookType) {
        this.id = id;
        this.addTime = addTime;
        this.author = author;
        this.coverPhoto = coverPhoto;
        this.name = name;
        this.price = price;
        this.status = status;
        this.press = press;
        this.bookType = bookType;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getAddTime() {
        return this.addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getCoverPhoto() {
        return this.coverPhoto;
    }

    public void setCoverPhoto(String coverPhoto) {
        this.coverPhoto = coverPhoto;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getPrice() {
        return this.price;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public Long getStatus() {
        return this.status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public Press getPress() {
        return this.press;
    }

    public void setPress(Press press) {
        this.press = press;
    }

    public BookType getBookType() {
        return this.bookType;
    }

    public void setBookType(BookType bookType) {
        this.bookType = bookType;
    }

    public Book id(Long id) {
        setId(id);
        return this;
    }

    public Book addTime(Date addTime) {
        setAddTime(addTime);
        return this;
    }

    public Book author(String author) {
        setAuthor(author);
        return this;
    }

    public Book coverPhoto(String coverPhoto) {
        setCoverPhoto(coverPhoto);
        return this;
    }

    public Book name(String name) {
        setName(name);
        return this;
    }

    public Book price(Long price) {
        setPrice(price);
        return this;
    }

    public Book status(Long status) {
        setStatus(status);
        return this;
    }

    public Book press(Press press) {
        setPress(press);
        return this;
    }

    public Book bookType(BookType bookType) {
        setBookType(bookType);
        return this;
    }


    @Override
    public String toString() {
        return "{" +
            " id='" + getId() + "'" +
            ", addTime='" + getAddTime() + "'" +
            ", author='" + getAuthor() + "'" +
            ", coverPhoto='" + getCoverPhoto() + "'" +
            ", name='" + getName() + "'" +
            ", price='" + getPrice() + "'" +
            ", status='" + getStatus() + "'" +
            ", press='" + getPress() + "'" +
            ", bookType='" + getBookType() + "'" +
            "}";
    }

}