package com.ytc.app6.model;

import java.util.Date;

public class LuckHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_history.id
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_history.create_time
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_history.name
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luck_history.prize_id
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private Prize prize;

    public LuckHistory() {
    }

    public LuckHistory(Long id, Date createTime, String name, Prize prize) {
        this.id = id;
        this.createTime = createTime;
        this.name = name;
        this.prize = prize;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Prize getPrize() {
        return this.prize;
    }

    public void setPrize(Prize prize) {
        this.prize = prize;
    }

    public LuckHistory id(Long id) {
        setId(id);
        return this;
    }

    public LuckHistory createTime(Date createTime) {
        setCreateTime(createTime);
        return this;
    }

    public LuckHistory name(String name) {
        setName(name);
        return this;
    }

    public LuckHistory prize(Prize prize) {
        setPrize(prize);
        return this;
    }


    @Override
    public String toString() {
        return "{" +
            " id='" + getId() + "'" +
            ", createTime='" + getCreateTime() + "'" +
            ", name='" + getName() + "'" +
            ", prize='" + getPrize() + "'" +
            "}";
    }

}