package com.ytc.app6.model;

public class Prize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.id
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.img
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.name
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.price
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.stock
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private Long stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.type
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    private Long type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.id
     *
     * @return the value of prize.id
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.id
     *
     * @param id the value for prize.id
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.img
     *
     * @return the value of prize.img
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.img
     *
     * @param img the value for prize.img
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.name
     *
     * @return the value of prize.name
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.name
     *
     * @param name the value for prize.name
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.price
     *
     * @return the value of prize.price
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.price
     *
     * @param price the value for prize.price
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.stock
     *
     * @return the value of prize.stock
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.stock
     *
     * @param stock the value for prize.stock
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.type
     *
     * @return the value of prize.type
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.type
     *
     * @param type the value for prize.type
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    public void setType(Long type) {
        this.type = type;
    }
}