package repository;

import com.ytc.app6.model.LuckHistory;

public interface LuckHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_history
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_history
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int insert(LuckHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_history
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int insertSelective(LuckHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_history
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    LuckHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_history
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int updateByPrimaryKeySelective(LuckHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luck_history
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int updateByPrimaryKey(LuckHistory record);
}