package repository;

import com.ytc.app6.model.Prize;

public interface PrizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int insert(Prize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int insertSelective(Prize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    Prize selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int updateByPrimaryKeySelective(Prize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated Fri Feb 04 08:31:39 CST 2022
     */
    int updateByPrimaryKey(Prize record);
}