package com.ytc.app3.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iii_user.id
     *
     * @mbggenerated Fri Feb 04 16:00:08 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iii_user.chk
     *
     * @mbggenerated Fri Feb 04 16:00:08 CST 2022
     */
    private String chk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iii_user.date
     *
     * @mbggenerated Fri Feb 04 16:00:08 CST 2022
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iii_user.flag
     *
     * @mbggenerated Fri Feb 04 16:00:08 CST 2022
     */
    private Long flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iii_user.name
     *
     * @mbggenerated Fri Feb 04 16:00:08 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iii_user.password
     *
     * @mbggenerated Fri Feb 04 16:00:08 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iii_user.user_type_id
     *
     * @mbggenerated Fri Feb 04 16:00:08 CST 2022
     */
    private UserType userType;

    public User() {
        System.out.println("user noargconstructor called");
        this.userType = new UserType();
        this.userType.setId(1L);
        this.flag = 1L;
    }

    public User(Long id, String chk, Date date, Long flag, String name, String password, UserType userType) {
        this.id = id;
        this.chk = chk;
        this.date = date;
        this.flag = flag;
        this.name = name;
        this.password = password;
        this.userType = userType;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getChk() {
        return this.chk;
    }

    public void setChk(String chk) {
        this.chk = chk;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Long getFlag() {
        return this.flag;
    }

    public void setFlag(Long flag) {
        this.flag = flag;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserType getUserType() {
        return this.userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    public User id(Long id) {
        setId(id);
        return this;
    }

    public User chk(String chk) {
        setChk(chk);
        return this;
    }

    public User date(Date date) {
        setDate(date);
        return this;
    }

    public User flag(Long flag) {
        setFlag(flag);
        return this;
    }

    public User name(String name) {
        setName(name);
        return this;
    }

    public User password(String password) {
        setPassword(password);
        return this;
    }

    public User userType(UserType userType) {
        setUserType(userType);
        return this;
    }

    @Override
    public String toString() {
        return "{" +
            " id='" + getId() + "'" +
            ", chk='" + getChk() + "'" +
            ", date='" + getDate() + "'" +
            ", flag='" + getFlag() + "'" +
            ", name='" + getName() + "'" +
            ", password='" + getPassword() + "'" +
            ", userType='" + getUserType() + "'" +
            "}";
    }

}